swagger: "2.0"
info: 
  version: "0.0.1"
  title: "storage"
  description: "A service for cloudmesh storage using swagger-2.0 specification and codegen"
  termsOfService: "http://swagger.io/terms/"
  contact: 
    name: "cloudmesh storage REST Service"
  license: 
    name: "Apache"
host: "localhost:8080"
basePath: "/cloudmesh/storage/v1"
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths: 
  /put:
    post:
      tags:
        - STORAGE
      operationId: storage.put
      description: "Returns list of files/blobs in the specified directory"
      parameters:
        - in: body
          name: params 
          description: "Provide the directory name in body of the request"
          schema: 
            $ref: "#/definitions/PUT"
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "Upload files/blobs"
  /get:
    get:
      tags:
        - STORAGE
      operationId: storage.get
      description: "Returns list of files/blobs in the specified directory"
      parameters:
        - in: query
          name: service 
          description: "Provide the service name in body of the request"
          type: string
          required: true
        - in: query
          name: source 
          description: "Provide the source path in body of the request"
          type: string
          required: true
        - in: query
          name: destination 
          description: "Provide the destination path in body of the request"
          type: string
          required: true
        - in: query
          name: recursive 
          description: "Provide the recursive option in body of the request"
          type: string
          required: false
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "get files/blobs"
          schema: 
            $ref: "#/definitions/LIST"
  /list:
    get:
      tags:
        - STORAGE
      operationId: storage.list
      description: "Returns list of files/blobs in the specified directory"
      parameters:
        - in: query
          name: service 
          description: "Provide the service name in body of the request"
          type: string
          required: true
        - in: query
          name: directory 
          description: "Provide the directory name in body of the request"
          type: string
          required: true
        - in: query
          name: recursive 
          description: "Provide the recursive option in body of the request"
          type: string
          required: false
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "list files/blobs"
          schema: 
            $ref: "#/definitions/LIST"
  /search:
    get:
      tags:
        - STORAGE
      operationId: storage.search
      description: "Returns list of files/blobs in the specified directory"
      parameters:
        - in: query
          name: service 
          description: "Provide the service name in body of the request"
          type: string
          required: true
        - in: query
          name: directory 
          description: "Provide the directory name in body of the request"
          type: string
          required: true
        - in: query
          name: filename 
          description: "Provide the directory name in body of the request"
          type: string
          required: true
        - in: query
          name: recursive 
          description: "Provide the recursive option in body of the request"
          type: string
          required: false
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "search files/blobs"
          schema: 
            $ref: "#/definitions/LIST"
  /delete:
    get:
      tags:
        - STORAGE
      operationId: storage.delete
      description: "Returns list of files/blobs in the specified directory"
      parameters:
        - in: query
          name: service 
          description: "Provide the service name in body of the request"
          type: string
          required: true
        - in: query
          name: source 
          description: "Provide the source name in body of the request"
          type: string
          required: true
        - in: query
          name: recursive 
          description: "Provide the recursive option in body of the request"
          type: string
          required: false
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "delete files/blobs"
          schema: 
            $ref: "#/definitions/LIST"
  /create_dir:
    get:
      tags:
        - STORAGE
      operationId: storage.create_dir
      description: "Returns list of files/blobs in the specified directory"
      parameters:
        - in: query
          name: service 
          description: "Provide the service name in body of the request"
          type: string
          required: true
        - in: query
          name: directory 
          description: "Provide the directory name in body of the request"
          type: string
          required: true
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "create directory"
          schema: 
            $ref: "#/definitions/LIST"

definitions:
  PUT:
    type: "object"
    required: 
      - "service"
      - "source"
      - "destination"
      - "recursive"
    properties: 
      service:
        type: "string"
      source:
        type: "string"
      destination:
        type: "string"
      recursive:
        type: "string"
  LIST:
    type: "object"
    required: 
      - "results"
    properties: 
      results:
        type: "string"
